version: '3.6'

services:
    listening-party-api:
        container_name: backend
        # image: node:14.7.0
        build: ./
        command: npm run dev
        working_dir: /listening-party-api
        ports:
            - "3001:3001"
        volumes: 
            - ./:/listening-party-api
        links:
            - redis
        environment: 
            REDIS_URI: redis://redis:6379
    redis:
        image: redis
        ports: 
            - "6379:6379"

